# Generated by Django 6.0.1 on 2026-05-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='submission_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], default='Manual', max_length=20),
        ),
    ]
