# Generated by Django 6.0.1 on 2026-05-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pirepsflight_submission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('if_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='allowedaircraft',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft'),
        ),
    ]
