# Generated by Django 6.0.1 on 2026-05-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aircraft_alter_allowedaircraft_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='category',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('GA', 'General Aviation'), ('Bizjet', 'Business Jet'), ('Cargo', 'Cargo'), ('Military', 'Military'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=15),
        ),
        migrations.CreateModel(
            name='AllowedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('GA', 'General Aviation'), ('Bizjet', 'Business Jet'), ('Cargo', 'Cargo'), ('Military', 'Military'), ('Uncategorized', 'Uncategorized')], max_length=15)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_categories', to='api.award')),
            ],
        ),
    ]
