# Generated by Django 6.0.1 on 2026-05-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_aircraft_category_allowedcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='aircraft',
            field=models.CharField(max_length=100),
        ),
    ]
