# Generated by Django 6.0.1 on 2026-05-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_pirepsflight_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livery',
            fields=[
                ('livery_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveries', to='api.aircraft')),
            ],
        ),
    ]
