# Generated by Django 6.0.1 on 2026-05-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_livery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='livery_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
