# Generated by Django 6.0.1 on 2026-05-16 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pirepsflight_livery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(blank=True, max_length=100)),
                ('vs_touchdown', models.IntegerField(default=0)),
                ('g_force', models.FloatField(default=1.0)),
                ('centerline', models.FloatField(default=0.0)),
                ('bounce_count', models.IntegerField(default=0)),
                ('light_infrac', models.JSONField(default=list)),
                ('status', models.CharField(default='WAITING', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pirep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_report', to='api.pirepsflight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
