# Generated by Django 6.0.1 on 2026-05-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_landingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='fuel_weight_kg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='ias_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='landing_lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='landing_lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='unstable_approaches',
            field=models.IntegerField(default=0),
        ),
    ]
