# Generated by Django 6.0.1 on 2026-05-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_landingreport_fuel_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='deductions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='flight_path',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
