# Generated by Django 6.0.1 on 2026-05-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_landingreport_deductions_landingreport_flight_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='distance_from_1kft',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
