# Generated by Django 6.0.1 on 2026-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_landingreport_distance_from_1kft'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='fuel_reserve_minutes',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
