# Generated by Django 6.0.1 on 2026-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_landingreport_fuel_reserve_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='gear_retraction_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='has_retractable_gear',
            field=models.BooleanField(default=False),
        ),
    ]
