# Generated by Django 6.0.1 on 2026-05-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_landingreport_gear_retraction_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='telemetry_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
