# Generated by Django 6.0.1 on 2026-05-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_pirepsflight_telemetry_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='telemetry_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
