# Generated by Django 6.0.1 on 2026-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_landingreport_telemetry_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active_pilot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reactivation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
