# Generated by Django 6.0.1 on 2026-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customuser_is_active_pilot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingreport',
            name='if_flight_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingreport',
            name='if_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
