# Generated by Django 6.0.1 on 2026-07-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tag',
            field=models.CharField(choices=[('NOTAM', 'NOTAM'), ('EVENTS', 'EVENTS'), ('WORLDTOUR', 'WORLDTOUR'), ('UPDATE', 'UPDATE')], default='UPDATE', max_length=20),
        ),
    ]
