# Generated by Django 6.0.1 on 2026-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_announcement_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='flight_type',
            field=models.CharField(choices=[('World Tour', 'World Tour'), ('Free Flight Pax', 'Free Flight Pax'), ('Free Flight Cargo', 'Free Flight Cargo')], default='World Tour', max_length=50),
        ),
        migrations.AlterField(
            model_name='pirepsflight',
            name='status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled')], default='Em análise', max_length=20),
        ),
    ]
