# Generated by Django 6.0.1 on 2026-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pirepsflight_flight_type_alter_pirepsflight_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(db_index=True, max_length=10)),
                ('iata', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('runways', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_url', models.URLField(max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
