# Generated by Django 6.0.1 on 2026-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='simbrief_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
