# Generated by Django 6.0.1 on 2026-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_customuser_simbrief_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='baggage_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pirepsflight',
            name='fuel_used_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pirepsflight',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
