# Generated by Django 6.0.1 on 2026-08-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_pirepsflight_baggage_kg_pirepsflight_fuel_used_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PROGRESSION', 'Progression'), ('OPERATIONS', 'Operations'), ('EXPLORATION', 'Exploration'), ('SPECIAL', 'Special')], default='PROGRESSION', max_length=50)),
                ('difficulty', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=20)),
                ('metric', models.CharField(choices=[('TOTAL_FLIGHTS', 'Total Flights'), ('TOTAL_HOURS', 'Total Hours'), ('TOTAL_BAGGAGE', 'Total Baggage (kg)'), ('TOTAL_PASSENGERS', 'Total Passengers'), ('TOTAL_AIRPORTS', 'Total Unique Airports'), ('PERFECT_LANDINGS', 'Consecutive Perfect Landings'), ('NIGHT_FLIGHT', 'Night Flight'), ('LONG_HAUL', 'Long Haul Flight (>12h)'), ('HEAVY_AIRCRAFT', 'Heavy Aircraft Flights')], max_length=50)),
                ('target_value', models.IntegerField(default=1)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('xp_reward', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
