# Generated by Django 6.0.1 on 2026-08-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='if_first_flight_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='metric',
            field=models.CharField(choices=[('TOTAL_FLIGHTS', 'Total Flights'), ('TOTAL_HOURS', 'Total Hours'), ('TOTAL_BAGGAGE', 'Total Baggage (kg)'), ('TOTAL_PASSENGERS', 'Total Passengers'), ('TOTAL_AIRPORTS', 'Total Unique Airports'), ('PERFECT_LANDINGS', 'Consecutive Perfect Landings'), ('NIGHT_FLIGHT', 'Night Flight'), ('LONG_HAUL', 'Long Haul Flight (>12h)'), ('HEAVY_AIRCRAFT', 'Heavy Aircraft Flights'), ('AIRBUS_FLIGHTS', 'Airbus Aircraft Flights'), ('BOEING_FLIGHTS', 'Boeing Aircraft Flights'), ('EMBRAER_FLIGHTS', 'Embraer Aircraft Flights'), ('CESSNA_FLIGHTS', 'Cessna Aircraft Flights'), ('PAX_FLIGHTS', 'Pax Flights'), ('CARGO_FLIGHTS', 'Cargo Flights'), ('WT_FLIGHTS', 'World Tour Flights'), ('SIMBRIEF_FLIGHTS', 'Simbrief Usage Flights'), ('SHORT_HAUL', 'Short Haul Flight (<3h)'), ('MEDIUM_HAUL', 'Medium Haul Flight (3-12h)'), ('LONG_HAUL', 'Long Haul Flight (>12h)'), ('PERFECT_LANDINGS', 'Perfect Landings (Score 10.0)'), ('TERRIBLE_LANDINGS', 'Terrible Landings (Score 0.0)'), ('EXPERT_SERVER', 'Expert Server Flights'), ('TRAINING_SERVER', 'Training Server Flights'), ('CASUAL_SERVER', 'Casual Server Flights'), ('IFC_COMMENT', 'IFC Topic Comment'), ('YEARS_SERVICE', 'Years of Service')], max_length=50),
        ),
    ]
