# Generated by Django 6.0.1 on 2026-08-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_achievement_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='if_atc_ops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='if_flights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='if_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='if_landings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='if_xp',
            field=models.IntegerField(default=0),
        ),
    ]
