# Generated by Django 6.0.1 on 2026-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_customuser_if_atc_ops_customuser_if_flights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='if_violations',
            field=models.IntegerField(default=0),
        ),
    ]
